import { redirect } from 'next/navigation';
import { PageShell } from '../components/Shell';
import { clearAdminCookie, isAdmin, setAdminCookie } from '@/lib/auth';
import { db, ensureSchema } from '@/lib/db';

async function login(formData: FormData) {'use server'; const password=String(formData.get('password')||''); if(password && password===process.env.ADMIN_PASSWORD){await setAdminCookie(); redirect('/admin')} redirect('/admin?erro=1')}
async function logout(){'use server'; await clearAdminCookie(); redirect('/admin')}
async function createActivity(formData: FormData){'use server'; if(!(await isAdmin())) redirect('/admin'); const title=String(formData.get('title')||'').trim(); const description=String(formData.get('description')||'').trim(); const location=String(formData.get('location')||'').trim(); const date=String(formData.get('date')||''); const eventPassword=String(formData.get('eventPassword')||'').trim(); if(!title||!date||!eventPassword) redirect('/admin?erro=atividade'); await ensureSchema(); await db()`INSERT INTO piratas_activities (title, description, location, activity_date, event_password) VALUES (${title}, ${description}, ${location}, ${date}, ${eventPassword})`; redirect('/admin?ok=1')}
async function deleteActivity(formData: FormData){'use server'; if(!(await isAdmin())) redirect('/admin'); const id=Number(formData.get('id')); if(id){await ensureSchema(); await db()`DELETE FROM piratas_activities WHERE id=${id}`} redirect('/admin')}
async function getActivities(){try{await ensureSchema();return await db()`SELECT a.id,a.title,a.description,a.location,a.activity_date,COUNT(t.id)::int AS total FROM piratas_activities a LEFT JOIN piratas_attendance t ON t.activity_id=a.id GROUP BY a.id ORDER BY a.activity_date DESC LIMIT 20`}catch{return[]}}

export default async function Admin({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const params=await searchParams; const admin=await isAdmin(); const activities=admin?await getActivities():[]; if(!admin){return <PageShell><main className="admin-wrap"><section className="card admin-panel"><span className="badge">Área protegida</span><h1>Admin</h1><p className="lead">Entra com a palavra-passe de administração para criar atividades.</p>{params.erro&&<p className="error">Palavra-passe inválida.</p>}<form className="form" action={login}><label>Palavra-passe</label><input name="password" type="password" required placeholder="ADMIN_PASSWORD"/><button type="submit">Entrar</button></form></section></main></PageShell>} return <PageShell><main className="admin-wrap"><section className="admin-panel"><div className="card"><div className="section-title"><span className="badge">Admin ativo</span><form action={logout}><button className="secondary" type="submit">Sair</button></form></div><h1>Painel Admin</h1>{params.ok&&<p className="success">Atividade criada.</p>}{params.erro&&<p className="error">Confirma os campos.</p>}</div><div className="activities section"><article className="card"><h3>Criar atividade</h3><form className="form" action={createActivity}><label>Título</label><input name="title" required placeholder="Ex: Farm de materiais"/><label>Data e hora</label><input name="date" type="datetime-local" required/><label>Local</label><input name="location" placeholder="Base / Ponto de encontro"/><label>Palavra-passe do evento</label><input name="eventPassword" required placeholder="Senha para os membros marcarem presença"/><label>Descrição</label><textarea name="description" placeholder="Objetivo, requisitos, itens a levar..."/><button type="submit">Publicar atividade</button></form></article><aside className="card"><h3>Atividades recentes</h3>{activities.map((a:any)=><div className="step" key={a.id}><b>{a.title}</b><p>{new Date(a.activity_date).toLocaleString('pt-PT')} • {a.total} presenças</p><form action={deleteActivity}><input type="hidden" name="id" value={a.id}/><button className="secondary" type="submit">Apagar</button></form></div>)}</aside></div></section></main></PageShell>}
